name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test website
        run: |
          test -f website/index.html
          echo "Website file exists"

      - name: Build Docker image
        run: |
          docker build -t lutfullahkhan13/myapp:latest ./myapp
          docker tag lutfullahkhan13/myapp:latest lutfullahkhan13/myapp:${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker push lutfullahkhan13/myapp:latest
          docker push lutfullahkhan13/myapp:${{ github.sha }}
  deploy:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Deploy application
        run: |
          cd /home/lutfullah/compose-project
          docker compose -f deploy-compose.yaml pull
          docker compose -f deploy-compose.yaml up -d
